export const app: string;
export const appBar: string;
export const company: string;
export const content: string;
export const header: string;
export const footer: string;
export const main: string;
export const input: string;
export const sideBar: string;
